apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
  {{- $portsFirstNum := (include "common.ports.firstContainerPort" .) | int }}
  {{- if ge $portsFirstNum 1 }}
    {{- include "common.service.ports" . | nindent 4 }}
  {{- else }}
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ include "common.containerPortName" . }}
      protocol: TCP
      name: {{ include "common.containerPortName" . }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
