{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.ui.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka-ui
{{- end }}