repos:
- url: 'https://grafana.github.io/helm-charts/index.yaml'
  namespace: grafana
- url: 'https://prometheus-community.github.io/helm-charts/index.yaml'
  namespace: prometheus-community
- url: 'https://prometheus-community.github.io/helm-charts/index.yaml'
  namespace: prometheus-community
- url: 'https://kubernetes.github.io/ingress-nginx'
  namespace: ingress-nginx