repos:
- url: 'https://grafana.github.io/helm-charts/index.yaml'
  repo: grafana/helm-charts
  namespace: grafana
- url: 'https://prometheus-community.github.io/helm-charts/index.yaml'
  repo: prometheus-community/helm-charts
  namespace: prometheus-community
- url: 'https://kubernetes.github.io/ingress-nginx'
  repo: kubernetes/ingress-nginx
  namespace: ingress-nginx