repos:
# - url: 'https://sir5kong.github.io/helm-charts-hub'
#   repo: sir5kong/helm-charts-hub
#   namespace: sir5kong
- url: 'https://grafana.github.io/helm-charts/index.yaml'
  repo: grafana/helm-charts
  namespace: grafana
- url: 'https://prometheus-community.github.io/helm-charts/index.yaml'
  repo: prometheus-community/helm-charts
  namespace: prometheus-community
- url: 'https://kubernetes.github.io/ingress-nginx'
  repo: kubernetes/ingress-nginx
  namespace: ingress-nginx
- url: 'https://itboon.github.io/bitnami-charts/index.yaml'
  repo: itboon/bitnami-charts
  namespace: bitnami
  chartsDir: charts-bitnami
