elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: 50m
    memory: "512Mi"
  limits:
    cpu: 1
    memory: "2Gi"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: kibana.example.com
      paths:
        - path: /
  tls: []
  #  - secretName: example-tls
  #    hosts:
  #      - kibana.example.com
