name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout bitnami/charts
        uses: actions/checkout@v3
        with:
          repository: bitnami/charts
          # path: my-tools
          fetch-depth: 25000
      -
        name: View Files
        run: |
          pwd
          ls -alh
      - 
        name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - 
        name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: charts
          # CR_RELEASE_NAME_TEMPLATE: "{{ .Name }}-chart-{{ .Version }}"
