name: OSS Upload

on:
  # schedule:
  #   - cron: '*/5 * * * *' # every 5 minutes
  # workflow_dispatch: # on button click
  push:
    branches:
      - main

jobs:
  oss:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Upload to OSS
        if: ${{ vars.OSS_MIRROR_ENABLED == 'true' }}
        shell: bash
        env:
          DL_URL_OSS: "https://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64"
          OSS_KEY_ID: "${{ secrets.OSS_KEY_ID }}"
          OSS_KEY_SECRET: "${{ secrets.OSS_KEY_SECRET }}"
          OSS_EP: "${{ vars.OSS_EP }}"
          OSS_BUCKET: "${{ vars.OSS_BUCKET }}"
          CHART_INDEX_URL: "${{ vars.CHART_INDEX_URL }}"
          MIRROR_HOST: "${{ vars.MIRROR_HOST }}"
        run: |
          export ALIOSS="${HOME}/bin/ossutil"
          mkdir -p $(dirname $ALIOSS)
          curl -o $ALIOSS -L $DL_URL_OSS
          chmod a+rx $ALIOSS
          $ALIOSS config -e $OSS_EP -i $OSS_KEY_ID -k $OSS_KEY_SECRET
          git branch -a
          index_url="https://grafana.github.io/helm-charts/index.yaml"
          curl -o /tmp/index.yaml -L "$index_url"
          head -n50 /tmp/index.yaml
          namespace='grafana'
          chart_base_url='https://helm-charts.itboon.top'
          if head -n50 /tmp/index.yaml | grep -E '^apiVersion:' ; then
            sed -i 's%https://github.com/\('$namespace'/helm-charts/releases\)%'$chart_base_url'/github/\1%' /tmp/index.yaml
            $ALIOSS cp -f /tmp/index.yaml \
              "oss://${OSS_BUCKET}/${namespace}/index.yaml" \
              --meta "content-type:text/plain; charset=utf-8"
          fi
