name: Publish docs via GitHub Pages

on:
  workflow_dispatch: ## on button click

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout main
      uses: actions/checkout@v3
    - 
      name: Deploy docs
      #uses: mhausenblas/mkdocs-deploy-gh-pages@master
      uses: sir5kong/mkdocs-deploy-gh-pages@master
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REMOTE_BRANCH: docs
        # CUSTOM_DOMAIN: optionaldomain.com
        # CONFIG_FILE: folder/mkdocs.yml
        # EXTRA_PACKAGES: build-base
        # GITHUB_DOMAIN: github.myenterprise.com
        # REQUIREMENTS: folder/requirements.txt