name: Publish docs via GitHub Pages

on:
  workflow_dispatch: ## on button click

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      run: git show remotes/origin/gh-pages:index.yaml > docs/index.yaml
    - 
      name: Deploy docs
      #uses: mhausenblas/mkdocs-deploy-gh-pages@master
      uses: sir5kong/mkdocs-deploy-gh-pages@master
      # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}