name: Sync Charts Index

on:
  workflow_dispatch: ## on button click

  schedule:
    - cron: '0 */6 * * *'  ## every 6 hours

  push:
    branches:
      - main

jobs:
  syncCharts:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get Charts
        if: ${{ vars.OSS_MIRROR_ENABLED == 'true' }}
        shell: bash
        env:
          DL_URL_OSS: "https://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64"
          CHART_BASE_URL: 'https://helm-charts.itboon.top'
          OSS_KEY_ID: "${{ secrets.OSS_KEY_ID }}"
          OSS_KEY_SECRET: "${{ secrets.OSS_KEY_SECRET }}"
          OSS_EP: "${{ vars.OSS_EP }}"
          OSS_BUCKET: "${{ vars.OSS_BUCKET }}"
          CHART_INDEX_URL: "${{ vars.CHART_INDEX_URL }}"
          MIRROR_HOST: "${{ vars.MIRROR_HOST }}"
        run: '.github/sync-charts.sh'
